apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jaycodesit-com-cert
spec:
  secretName: jaycodesit-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  commonName: jaycodesit.com
  dnsNames:
    - jaycodesit.com
    - www.jaycodesit.com
