apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jaycodesit-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: microk8s-hostpath
