apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jaycodesit-com-cert
spec:
  secretName: jaycodesit-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  commonName: jaycodesit.com
  dnsNames:
    - jaycodesit.com
    - www.jaycodesit.com

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: jjwood2004@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          cloudflare:
            email: jjwood2004@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-key

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaycodesit-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  tls:
    - hosts:
        - jaycodesit.com
        - www.jaycodesit.com
      secretName: jaycodesit-com-tls
  rules:
    - host: jaycodesit.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jaycodesit-wordpress
                port:
                  number: 80
    - host: www.jaycodesit.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jaycodesit-wordpress
                port:
                  number: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: jaycodesit-wordpress-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jaycodesit-wordpress
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
