apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaycodesit-wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaycodesit-wordpress
  template:
    metadata:
      labels:
        app: jaycodesit-wordpress
    spec:
      containers:
        - name: wordpress
          image: jaycodesit/site:TAG_PLACEHOLDER
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: jaycodesit-mysql
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: jaycodesit-mysql-secret
                  key: mysql-user
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jaycodesit-mysql-secret
                  key: mysql-password
            - name: WORDPRESS_DB_NAME
              value: wordpress
            - name: AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: wordpress-jaycodesit-secrets
                  key: AUTH_KEY
            - name: SECURE_AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: wordpress-jaycodesit-secrets
                  key: SECURE_AUTH_KEY
            - name: LOGGED_IN_KEY
              valueFrom:
                secretKeyRef:
                  name: wordpress-jaycodesit-secrets
                  key: LOGGED_IN_KEY
            - name: NONCE_KEY
              valueFrom:
                secretKeyRef:
                  name: wordpress-jaycodesit-secrets
                  key: NONCE_KEY
            - name: AUTH_SALT
              valueFrom:
                secretKeyRef:
                  name: wordpress-jaycodesit-secrets
                  key: AUTH_SALT
            - name: SECURE_AUTH_SALT
              valueFrom:
                secretKeyRef:
                  name: wordpress-jaycodesit-secrets
                  key: SECURE_AUTH_SALT
            - name: LOGGED_IN_SALT
              valueFrom:
                secretKeyRef:
                  name: wordpress-jaycodesit-secrets
                  key: LOGGED_IN_SALT
            - name: NONCE_SALT
              valueFrom:
                secretKeyRef:
                  name: wordpress-jaycodesit-secrets
                  key: NONCE_SALT
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/jaycodesit-f6c85665a3fc.json # Path to service account JSON
          volumeMounts:
            - name: wordpress-uploads-storage
              mountPath: /var/www/html/wp-content/uploads
            - name: gdrive-secret
              mountPath: /var/secrets/google
              readOnly: true
      volumes:
        - name: wordpress-uploads-storage
          persistentVolumeClaim:
            claimName: jaycodesit-wordpress-uploads-pvc
        - name: gdrive-secret
          secret:
            secretName: gdrive-service-account # Name of the secret containing your service account JSON

---
apiVersion: v1
kind: Service
metadata:
  name: jaycodesit-wordpress
spec:
  type: NodePort
  selector:
    app: jaycodesit-wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jaycodesit-wordpress-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath
  hostPath:
    path: /mnt/data/wordpress

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jaycodesit-wordpress-uploads-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: microk8s-hostpath

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: jaycodesit-wordpress-cron
spec:
  schedule: "*/15 * * * *"  # Runs every 15 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: wordpress-cron
              image: jaycodesit/site:TAG_PLACEHOLDER
              imagePullPolicy: Always
              command: ["/bin/bash", "-c", "/usr/local/sbin/backup.sh"]
              env:
                - name: WORDPRESS_DB_HOST
                  value: jaycodesit-mysql
                - name: WORDPRESS_DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: jaycodesit-mysql-secret
                      key: mysql-user
                - name: WORDPRESS_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: jaycodesit-mysql-secret
                      key: mysql-password
                - name: WORDPRESS_DB_NAME
                  value: wordpress
                - name: AUTH_KEY
                  valueFrom:
                    secretKeyRef:
                      name: wordpress-jaycodesit-secrets
                      key: AUTH_KEY
                - name: SECURE_AUTH_KEY
                  valueFrom:
                    secretKeyRef:
                      name: wordpress-jaycodesit-secrets
                      key: SECURE_AUTH_KEY
                - name: LOGGED_IN_KEY
                  valueFrom:
                    secretKeyRef:
                      name: wordpress-jaycodesit-secrets
                      key: LOGGED_IN_KEY
                - name: NONCE_KEY
                  valueFrom:
                    secretKeyRef:
                      name: wordpress-jaycodesit-secrets
                      key: NONCE_KEY
                - name: AUTH_SALT
                  valueFrom:
                    secretKeyRef:
                      name: wordpress-jaycodesit-secrets
                      key: AUTH_SALT
                - name: SECURE_AUTH_SALT
                  valueFrom:
                    secretKeyRef:
                      name: wordpress-jaycodesit-secrets
                      key: SECURE_AUTH_SALT
                - name: LOGGED_IN_SALT
                  valueFrom:
                    secretKeyRef:
                      name: wordpress-jaycodesit-secrets
                      key: LOGGED_IN_SALT
                - name: NONCE_SALT
                  valueFrom:
                    secretKeyRef:
                      name: wordpress-jaycodesit-secrets
                      key: NONCE_SALT
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /var/secrets/google/jaycodesit-f6c85665a3fc.json  # Path to service account JSON
              volumeMounts:
                - name: wordpress-uploads-storage
                  mountPath: /var/www/html/wp-content/uploads
                - name: gdrive-secret
                  mountPath: /var/secrets/google
                  readOnly: true
          volumes:
            - name: wordpress-uploads-storage
              persistentVolumeClaim:
                claimName: jaycodesit-wordpress-uploads-pvc
            - name: gdrive-secret
              secret:
                secretName: gdrive-service-account  # Name of the secret containing your service account JSON
          restartPolicy: OnFailure
