apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: jaycodesit-wordpress-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jaycodesit-wordpress
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
