apiVersion: v1
kind: PersistentVolume
metadata:
  name: jaycodesit-wordpress-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath
  hostPath:
    path: /mnt/data/wordpress
