apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaycodesit-wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaycodesit-wordpress
  template:
    metadata:
      labels:
        app: jaycodesit-wordpress
    spec:
      containers:
        - name: wordpress
          image: jaycodesit/site:TAG_PLACEHOLDER
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: jaycodesit-mysql
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: jaycodesit-mysql-secret
                  key: mysql-user
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jaycodesit-mysql-secret
                  key: mysql-password
            - name: WORDPRESS_DB_NAME
              value: wordpress
            - name: AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: wordpress-jaycodesit-secrets
                  key: AUTH_KEY
            - name: SECURE_AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: wordpress-jaycodesit-secrets
                  key: SECURE_AUTH_KEY
            - name: LOGGED_IN_KEY
              valueFrom:
                secretKeyRef:
                  name: wordpress-jaycodesit-secrets
                  key: LOGGED_IN_KEY
            - name: NONCE_KEY
              valueFrom:
                secretKeyRef:
                  name: wordpress-jaycodesit-secrets
                  key: NONCE_KEY
            - name: AUTH_SALT
              valueFrom:
                secretKeyRef:
                  name: wordpress-jaycodesit-secrets
                  key: AUTH_SALT
            - name: SECURE_AUTH_SALT
              valueFrom:
                secretKeyRef:
                  name: wordpress-jaycodesit-secrets
                  key: SECURE_AUTH_SALT
            - name: LOGGED_IN_SALT
              valueFrom:
                secretKeyRef:
                  name: wordpress-jaycodesit-secrets
                  key: LOGGED_IN_SALT
            - name: NONCE_SALT
              valueFrom:
                secretKeyRef:
                  name: wordpress-jaycodesit-secrets
                  key: NONCE_SALT
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html/wp-content
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: jaycodesit-wordpress-pvc
