apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaycodesit-wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaycodesit-wordpress
  template:
    metadata:
      labels:
        app: jaycodesit-wordpress
    spec:
      containers:
        - name: wordpress
          image: jaycodesit/site:latest
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_URL
              value: http://www.jaycodesit.com
            - name: WORDPRESS_DB_HOST
              value: jaycodesit-mysql
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: jaycodesit-mysql-secret
                  key: mysql-user
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jaycodesit-mysql-secret
                  key: mysql-password
            - name: WORDPRESS_DB_NAME
              value: wordpress
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html/wp-content
          readinessProbe:
            httpGet:
              path: /index.php  # Path to check on the container
              port: 80          # Port number within the container
            initialDelaySeconds: 10  # Wait this long before first probe
            periodSeconds: 5         # Probe every 5 seconds
            failureThreshold: 8       # Consider the probe failed after 8 attempts
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: jaycodesit-wordpress-pvc
