name: Deploy to Kubernetes

on:
  push:
    branches:
      - main
    tags:
      - '*-release'  # Triggers on tags like 'v1.0.0-release', 'v2.1-release', etc.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: jaycodesit/site

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          file: ./config/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBECONFIG }}

      - name: Create Kubernetes secrets and apply manifests
        run: |
          if ! kubectl get secret jaycodesit-mysql-secret > /dev/null 2>&1; then
            kubectl create secret generic jaycodesit-mysql-secret \
              --from-literal=mysql-root-password=${{ secrets.MYSQL_ROOT_PASSWORD }} \
              --from-literal=mysql-user=${{ secrets.MYSQL_USER }} \
              --from-literal=mysql-password=${{ secrets.MYSQL_PASSWORD }}
          fi
          kubectl apply -f ./kube/


      - name: Update WordPress Deployment Image
        run: kubectl set image deployment/jaycodesit-wordpress wordpress=jaycodesit/site:main

