name: Deploy to Kubernetes

on:
  push:
    tags:
      - '*-release'  # Triggers on tags like 'v1.0.0-release', 'v2.1-release', etc.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Git tag
        id: extract_tag
        run: echo "GIT_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.4.0
        with:
          images: jaycodesit/site

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          dev: no

      - name: Check files
        run: cat src/plugins/contact-form-7/wp-contact-form-7.php

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./config/Dockerfile
          push: true
          tags: |
            jaycodesit/site:latest
            jaycodesit/site:${{ env.GIT_TAG }}
          labels: ${{ steps.meta.outputs.labels }}

      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBECONFIG }}

      - name: Create Kubernetes secrets and apply manifests
        run: |
          if ! kubectl get secret jaycodesit-mysql-secret > /dev/null 2>&1; then
            kubectl create secret generic jaycodesit-mysql-secret \
              --from-literal=mysql-root-password=${{ secrets.MYSQL_ROOT_PASSWORD }} \
              --from-literal=mysql-user=${{ secrets.MYSQL_USER }} \
              --from-literal=mysql-password=${{ secrets.MYSQL_PASSWORD }}
          fi
          # Replace TAG_PLACEHOLDER with the Git tag
          sed "s/TAG_PLACEHOLDER/${{ env.GIT_TAG }}/g" ./kube/wordpress-deploy.yml | kubectl apply -f -

      - name: Update WordPress Deployment Image
        run: kubectl set image deployment/jaycodesit-wordpress wordpress=jaycodesit/site:${{ env.GIT_TAG }}
