name: Deploy to Kubernetes

on:
  push:
    branches:
      - main
    tags:
      - '*-release'  # Triggers on tags like 'v1.0.0-release', 'v2.1-release', etc.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t jaycodesit/site:latest .
          docker push jaycodesit/site:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.20.0'  # Adjust to your preferred kubectl version

      - name: Set up Kubeconfig
        env:
          KUBECONFIG_DATA: ${{ secrets.KUBECONFIG }}
        run: |
          echo $KUBECONFIG_DATA | base64 --decode > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/mysql-secret.yaml
          kubectl apply -f k8s/mysql-pvc.yaml
          kubectl apply -f k8s/wordpress-pvc.yaml
          kubectl apply -f k8s/mysql-deployment.yaml
          kubectl apply -f k8s/mysql-service.yaml
          kubectl apply -f k8s/wordpress-deployment.yaml
          kubectl apply -f k8s/wordpress-service.yaml

      - name: Update WordPress Deployment Image
        run: kubectl set image deployment/wordpress wordpress=jaycodesit/site:latest

