name: Deploy to Kubernetes

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Git tag
        id: extract_tag
        run: echo "GIT_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: jaycodesit/site

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          dev: no

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./config/Dockerfile
          push: true
          tags: |
            jaycodesit/site:latest
            jaycodesit/site:${{ env.GIT_TAG }}
          labels: ${{ steps.meta.outputs.labels }}

      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBECONFIG }}

      - name: Apply Kube Manifests
        run: |
          sed -i "s/TAG_PLACEHOLDER/${{ env.GIT_TAG }}/g" ./kube/wordpress.yml
          cat ./kube/wordpress.yml  # Debugging step
          kubectl apply -f ./kube/

      - name: Update WordPress Deployment Image
        run: kubectl set image deployment/jaycodesit-wordpress wordpress=jaycodesit/site:${{ env.GIT_TAG }}

      - name: Update CronJob Image
        run: kubectl set image cronjob/jaycodesit-wordpress-cron wordpress-cron=jaycodesit/site:${{ env.GIT_TAG }}
